/** @type {import('next').NextConfig} */

const {
  SUPABASE_POSTGRES_POSTGRES_URL,
  SUPABASE_POSTGRES_POSTGRES_PRISMA_URL,
  SUPABASE_POSTGRES_SUPABASE_URL,
  SUPABASE_POSTGRES_NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_POSTGRES_POSTGRES_URL_NON_POOLING,
  SUPABASE_POSTGRES_SUPABASE_JWT_SECRET,
  SUPABASE_POSTGRES_POSTGRES_USER,
  SUPABASE_POSTGRES_NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_POSTGRES_POSTGRES_PASSWORD,
  SUPABASE_POSTGRES_POSTGRES_DATABASE,
  SUPABASE_POSTGRES_SUPABASE_SERVICE_ROLE_KEY,
  SUPABASE_POSTGRES_POSTGRES_HOST
} = process.env;

const nextConfig = {
  images: {
    domains: ["nus.edu.sg"]
  },
  env: {
    SUPABASE_POSTGRES_POSTGRES_URL,
    SUPABASE_POSTGRES_POSTGRES_PRISMA_URL,
    SUPABASE_POSTGRES_SUPABASE_URL,
    SUPABASE_POSTGRES_NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_POSTGRES_POSTGRES_URL_NON_POOLING,
    SUPABASE_POSTGRES_SUPABASE_JWT_SECRET,
    SUPABASE_POSTGRES_POSTGRES_USER,
    SUPABASE_POSTGRES_NEXT_PUBLIC_SUPABASE_ANON_KEY,
    SUPABASE_POSTGRES_POSTGRES_PASSWORD,
    SUPABASE_POSTGRES_POSTGRES_DATABASE,
    SUPABASE_POSTGRES_SUPABASE_SERVICE_ROLE_KEY,
    SUPABASE_POSTGRES_POSTGRES_HOST
  }
};
module.exports = nextConfig;

